CREATE TABLE IF NOT EXISTS images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  width INT NOT NULL, 
  height INT NOT NULL,
  components INT NOT NULL,
  contents BLOB NOT NULL
);

CREATE UNIQUE INDEX idx_images_name ON images (name);

CREATE TABLE IF NOT EXISTS spritesheets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  width INT NOT NULL,
  height INT NOT NULL
);

CREATE UNIQUE INDEX idx_spritesheets_name ON spritesheets (name);

CREATE TABLE IF NOT EXISTS sprites (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  spritesheet VARCHAR(255) NOT NULL,
  x INT NOT NULL,
  y INT NOT NULL,
  width INT NOT NULL,
  height INT NOT NULL
);

CREATE UNIQUE INDEX idx_sprites_name ON sprites (name);
CREATE INDEX idx_sprites_spritesheet ON sprites (spritesheet);

CREATE TABLE IF NOT EXISTS audios (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  contents BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS scripts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  contents BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS shaders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  contents BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS fonts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  contents BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  contents BLOB NOT NULL
)
